apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-service
spec:
  selector:
    app: cloud-native-app
  ports:
    - protocol: TCP
      port: 80       # External port exposed by the service
      targetPort: 3000 # Port your application is running on inside the container
  type: LoadBalancer  # Use "NodePort" if running locally, "ClusterIP" for internal access
